---
openapi: 3.1.0
info:
  title: Scene Builder Agent
  description: Generates validated Scene JSON from natural language prompts
  version: 0.1.0
paths:
  "/v1/agent/scene":
    post:
      summary: Generate Scene
      description: |-
        POST /v1/agent/scene
        Accepts a natural language prompt and optional constraints
        Runs the full scene-building pipeline and returns plan + scene JSON
      operationId: generate_scene_v1_agent_scene_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SceneRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SceneResponse"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    Action:
      properties:
        id:
          type: string
          title: Id
        type:
          type: string
          enum:
          - video
          - image
          - audio
          - text
          title: Type
        startSec:
          type: number
          title: Startsec
        durationSec:
          type: number
          title: Durationsec
        props:
          additionalProperties: true
          type: object
          title: Props
        effects:
          anyOf:
          - items:
              "$ref": "#/components/schemas/Effect"
            type: array
          - type: 'null'
          title: Effects
      type: object
      required:
      - id
      - type
      - startSec
      - durationSec
      - props
      title: Action
    Effect:
      properties:
        name:
          type: string
          title: Name
        props:
          additionalProperties: true
          type: object
          title: Props
      type: object
      required:
      - name
      title: Effect
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Meta:
      properties:
        aspectRatio:
          anyOf:
          - type: string
          - type: 'null'
          title: Aspectratio
          default: '16:9'
        fps:
          anyOf:
          - type: integer
          - type: 'null'
          title: Fps
          default: 30
        totalDurationSec:
          type: number
          title: Totaldurationsec
        generator:
          anyOf:
          - type: string
          - type: 'null'
          title: Generator
          default: scene-builder-agent
        version:
          anyOf:
          - type: string
          - type: 'null'
          title: Version
          default: 1.0.0
      type: object
      required:
      - totalDurationSec
      title: Meta
    Row-Input:
      properties:
        id:
          type: string
          title: Id
        kind:
          type: string
          enum:
          - video
          - image
          - audio
          - text
          - captions
          title: Kind
        actions:
          items:
            "$ref": "#/components/schemas/Action"
          type: array
          title: Actions
        transitions:
          anyOf:
          - items:
              "$ref": "#/components/schemas/Effect"
            type: array
          - type: 'null'
          title: Transitions
      type: object
      required:
      - id
      - kind
      - actions
      title: Row
    Row-Output:
      properties:
        id:
          type: string
          title: Id
        kind:
          type: string
          enum:
          - video
          - image
          - audio
          - text
          - captions
          title: Kind
        actions:
          items:
            "$ref": "#/components/schemas/Action"
          type: array
          title: Actions
        transitions:
          anyOf:
          - items:
              "$ref": "#/components/schemas/Effect"
            type: array
          - type: 'null'
          title: Transitions
      type: object
      required:
      - id
      - kind
      - actions
      title: Row
    SceneInputConstraints:
      properties:
        totalDurationSec:
          anyOf:
          - type: number
          - type: 'null'
          title: Totaldurationsec
        aspectRatio:
          anyOf:
          - type: string
          - type: 'null'
          title: Aspectratio
        fps:
          anyOf:
          - type: integer
          - type: 'null'
          title: Fps
        language:
          anyOf:
          - type: string
          - type: 'null'
          title: Language
          default: en
        deterministic:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Deterministic
          default: false
      type: object
      title: SceneInputConstraints
    SceneItem-Input:
      properties:
        id:
          type: string
          title: Id
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
          default: ''
        durationSec:
          type: number
          title: Durationsec
        rows:
          items:
            "$ref": "#/components/schemas/Row-Input"
          type: array
          title: Rows
      type: object
      required:
      - id
      - durationSec
      - rows
      title: SceneItem
    SceneItem-Output:
      properties:
        id:
          type: string
          title: Id
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
          default: ''
        durationSec:
          type: number
          title: Durationsec
        rows:
          items:
            "$ref": "#/components/schemas/Row-Output"
          type: array
          title: Rows
      type: object
      required:
      - id
      - durationSec
      - rows
      title: SceneItem
    SceneRequest:
      properties:
        prompt:
          type: string
          title: Prompt
          description: Natural language prompt describing the desired scene(s)
        constraints:
          anyOf:
          - "$ref": "#/components/schemas/SceneInputConstraints"
          - type: 'null'
          description: Optional generation constraints such as duration, fps, aspect
            ratio, deterministic flag
      type: object
      required:
      - prompt
      title: SceneRequest
    SceneResponse:
      properties:
        plan:
          additionalProperties: true
          type: object
          title: Plan
        scene:
          "$ref": "#/components/schemas/SceneSchema-Output"
      type: object
      required:
      - plan
      - scene
      title: SceneResponse
    SceneSchema-Input:
      properties:
        scenes:
          items:
            "$ref": "#/components/schemas/SceneItem-Input"
          type: array
          title: Scenes
        meta:
          "$ref": "#/components/schemas/Meta"
      type: object
      required:
      - scenes
      - meta
      title: SceneSchema
    SceneSchema-Output:
      properties:
        scenes:
          items:
            "$ref": "#/components/schemas/SceneItem-Output"
          type: array
          title: Scenes
        meta:
          "$ref": "#/components/schemas/Meta"
      type: object
      required:
      - scenes
      - meta
      title: SceneSchema
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
